---
# tasks file for project's preparations

- name: Setting sysctl options
  become: yes
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    reload: yes
    state: present
  with_dict:
    vm.overcommit_memory: 1
    net.core.somaxconn: 1024
    fs.file-max: 10000

- name: Creating project folder
  ansible.builtin.file:
    path: "{{ global.home }}/{{ role_name }}"
    state: directory
