galaxy_info:
  author: Alex Brazovsky
  description: This role creates and configures common resources for the projects
  license: Apache
  min_ansible_version: 2.1
  platforms:
    - name: Ubuntu
      versions:
        - focal
