---
# handlers file for mysql
- name: Reload service
  become: true
  ansible.builtin.service:
    name: "{{ global.service_prefix }}@{{ role_name }}"
    state: restarted
  listen: "Reload MySQL project"
