---
# tasks file for Docker and its dependencies

- name: Install Docker dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - net-tools
    state: present
    update_cache: true

- name: Import GPG key for Docker
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable  # noqa 204

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true

- name: Install Docker-Compose
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/download/{{ common.docker_compose.version }}/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture | lower }}"  # noqa 204
    dest: "{{ common.docker_compose.location }}"
    mode: '0755'

- name: Enable Docker service
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
  with_items:
    - docker
    - containerd

- name: Add ansible user to Docker group
  ansible.builtin.user:
    name: "{{ ansible_user_id | string }}"
    groups: docker
