galaxy_info:
  author: Alex Brazovsky
  description: This role creates and configures Redis cluster using Docker as a system service
  license: Apache
  min_ansible_version: 2.1
  platforms:
    - name: Ubuntu
      versions:
        - focal

dependencies:
  - role: common
    become: true
