---
# handlers file for Rabbitmq
- name: Reload service
  become: true
  ansible.builtin.service:
    name: "{{ global.service_prefix }}@{{ role_name }}"
    state: restarted
  listen: "Reload RabbitMQ project"
