---
# handlers file for Rabbitmq
  - name: Reload service
    become: yes
    ansible.builtin.service:
      name: "{{ global.service_prefix }}@{{ role_name }}"
      state: restarted
    listen: "Reload RabbitMQ project"
