---
# handlers file for redis
- name: Reload service
  become: true
  ansible.builtin.service:
    name: "{{ global.service_prefix }}@{{ role_name }}"
    state: restarted
  listen: "Reload Redis project"
