galaxy_info:
  author: Alex Brazovsky
  description: This role creates and configures MySQL cluster using Docker as a system service
  license: license (GPL-2.0-or-later, MIT, etc)
  min_ansible_version: 2.1

dependencies:
  - role: common
    become: yes
