version: '3.8'

services:
  master:
    hostname: redis_1
    image: "${REDIS_IMAGE}"
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD
    expose:
      - "${REDIS_PORT}"
    volumes: &redis_data
      - type: bind
        source: ./data
        target: /bitnami
    networks: &network
      - redis

  replica_1: &replica
    hostname: redis_2
    image: "${REDIS_IMAGE}"
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=master
      - REDIS_MASTER_PORT_NUMBER=${REDIS_PORT}
      - REDIS_MASTER_PASSWORD="${REDIS_PASSWORD}"
      - REDIS_PASSWORD
    expose:
      - "${REDIS_PORT}"
    volumes: *redis_data
    networks: *network
    depends_on:
      - master

  replica_2:
    << : *replica
    hostname: redis_3

  sentinel:
    scale: 3
    image: "${REDIS_SENTINEL_IMAGE}"
    environment:
      - REDIS_MASTER_HOST=master
      - REDIS_MASTER_PORT_NUMBER=${REDIS_PORT}
      - REDIS_MASTER_PASSWORD="${REDIS_PASSWORD}"
      - REDIS_SENTINEL_PORT_NUMBER=${REDIS_SENTINEL_PORT}
      - REDIS_SENTINEL_QUORUM=2
      - REDIS_SENTINEL_RESOLVE_HOSTNAMES=yes
    expose:
      - "${REDIS_SENTINEL_PORT}"
    networks: *network
    depends_on:
      - master
      - replica_1
      - replica_2

  haproxy:
    image: "${REDIS_HAPROXY_IMAGE}"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
      - "${REDIS_STATS_PORT}:${REDIS_STATS_PORT}"
    environment:
      - REDIS_PORT
      - REDIS_STATS_PORT
      - REDIS_PASSWORD
    volumes:
      - type: bind
        source: ./haproxy.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg
        read_only: true
    networks: *network
    depends_on:
      - master
      - replica_1
      - replica_2

networks:
  redis:
    name: redis_network
